### ISSUE TITLE
Constructor Order(int,String,int) undefined

### ISSUE THREAD

**Issue by karshil2309** [Java-Techie-jt/spring-camel-rest-dsl#1]
@PostConstruct
	public void initDB() {
		list.add(new Order(67, "Mobile", 5000));
		list.add(new Order(89, "Book", 400));
		list.add(new Order(45, "AC", 15000));
		list.add(new Order(67, "Shoes", 4000));
}
Here getting Compile time Error of Constructor not defined. Please check @basahota

**Comment by basahota** [comment]
Did you added @AllArgsConstructor Lombok annotation if yes then please do configure Lombok in your IDE

**Comment by karshil2309** [comment]
@basahota  Yes Let me share my screenshot. Now configure Lombok, I mean just adding dependency in pom.xml it will work, i do not have to set explicitly or do i have to ?

![Screenshot (12)](https://user-images.githubusercontent.com/37497287/96692939-46e66280-13a4-11eb-8793-4e5107a6e5ad.png)


![Screenshot (13)](https://user-images.githubusercontent.com/37497287/96692951-4b128000-13a4-11eb-880b-7196f737095c.png)

**Comment by basahota** [comment]
Adding dependency is not enough , You need to set it explicitly .

**Comment by karshil2309** [comment]
okay thank you, will do that

**Comment by yash0923** [comment]
did you solve the issue, AND IF YOU SOLVED THE ISSUE, will you tell where you done changes.

**Comment by karshil2309** [comment]
@yash0923 Yes u need to add Lombok jar into eclipse and configure it. Automatically you will see the annotations methods and constructors besides the panel. For reference visit this link : https://stackoverflow.com/questions/22310414/how-to-configure-lombok-in-eclipse-luna

**Comment by yash0923** [comment]
i already added lambok jar file in pom.xml file

**Comment by karshil2309** [comment]
> i already added lambok jar file in pom.xml file

It wont work like that, need to configure to eclipse then only dependency will work.

**Comment by yash0923** [comment]
Okay thankyou so much @karshil2309
